export const METRIC_DEFS = [
  {
    key: 'war_chest_ratio',
    label: 'War Chest Ratio',
    type: 'raw',
    colorType: 'warChest',
    meaning: 'Cash ÷ Total Debt. Measures how many times a company can cover its entire debt load using cash on hand. A ratio above 1 means the company has more cash than debt — it is net-cash positive.',
    scale: '< 0.5 = Danger (Red) · 0.5–1.0 = Caution (Yellow) · 1.0–2.0 = Healthy (Green) · > 2.0 = Elite (Bright Green)',
  },
  {
    key: 'fcf',
    label: 'Free Cash Flow',
    type: 'curr',
    colorType: 'fcf',
    meaning: 'Cash remaining after all operating expenses and capital expenditures. This is the "real" profit — money that can be used to buy back shares, pay dividends, make acquisitions, or reduce debt. Positive FCF means the business funds itself.',
    scale: 'Strongly Negative = Cash Burning (Red) · Slightly Negative = Early Stage OK · Positive = Self-Funding (Green) · Large Positive = Cash Machine (Bright Green)',
  },
  {
    key: 'gross_margin',
    label: 'Gross Margin',
    type: 'pct',
    colorType: 'margin',
    meaning: '(Revenue − Cost of Goods Sold) ÷ Revenue. The percentage of each dollar of revenue kept after direct production costs. High gross margins signal pricing power and a competitive moat. Software companies often exceed 70%. Physical goods are typically 20–40%.',
    scale: '< 20% = Tight / Commodity (Red) · 20–35% = Acceptable · 35–60% = Strong · > 60% = World-Class (Bright Green)',
  },
  {
    key: 'forward_pe',
    label: 'Forward P/E',
    type: 'raw',
    colorType: 'pe',
    meaning: 'Stock price ÷ next 12-month estimated earnings per share. Tells you how much the market is paying for each dollar of future profit. A low P/E can signal undervaluation or low expected growth. A high P/E reflects growth expectations — but also high risk if those expectations aren\'t met.',
    scale: '< 12 = Potentially Cheap (Green) · 12–25 = Fair · 25–40 = Growth Premium · > 40 = Speculative / Expensive (Red)',
  },
  {
    key: 'revenue_yoy',
    label: 'Revenue YoY',
    type: 'pct',
    colorType: 'margin',
    meaning: 'Year-over-year percentage change in total revenue. The most direct measure of demand for a company\'s products or services. Sustained revenue growth above 15% is considered hypergrowth. Below 0% indicates demand destruction.',
    scale: '< 0% = Contracting (Red) · 0–8% = Slow Growth · 8–20% = Healthy · > 20% = Hypergrowth (Bright Green)',
  },
  {
    key: 'operating_margin',
    label: 'Operating Margin',
    type: 'pct',
    colorType: 'margin',
    meaning: 'Operating Income ÷ Revenue. The percentage of revenue left after all operating costs (salaries, rent, R&D, marketing) but before interest and taxes. Shows how efficiently management runs the core business.',
    scale: '< 0% = Operating Loss (Red) · 0–10% = Thin · 10–25% = Healthy · > 25% = Exceptional (Bright Green)',
  },
  {
    key: 'net_margin',
    label: 'Net Margin',
    type: 'pct',
    colorType: 'margin',
    meaning: 'Net Income ÷ Revenue. The percentage of revenue that becomes profit after every expense including taxes and interest. The "bottom line" of profitability. Varies widely by industry.',
    scale: '< 0% = Unprofitable (Red) · 0–5% = Thin · 5–15% = Solid · > 15% = Strong (Green)',
  },
  {
    key: 'trailing_pe',
    label: 'Trailing P/E',
    type: 'raw',
    colorType: 'pe',
    meaning: 'Stock price ÷ actual earnings per share over the last 12 months. Unlike forward P/E, this uses real reported earnings rather than estimates — less optimistic but more reliable. Useful for comparing against the forward P/E to gauge market expectations.',
    scale: '< 12 = Value Range (Green) · 12–25 = Normal · 25–40 = Premium · > 40 = Expensive (Red)',
  },
  {
    key: 'ps_ratio',
    label: 'P/S Ratio',
    type: 'raw',
    colorType: 'pe',
    meaning: 'Price ÷ Sales (Revenue) per share. Most useful for companies without profits yet. Tells you how much the market values each dollar of revenue. Common for early-stage tech companies where earnings are negative. A low P/S means the market undervalues the revenue base.',
    scale: '< 2× = Cheap Revenue · 2–8× = Normal for Tech · 8–20× = High Growth Premium · > 20× = Speculative (Red)',
  },
  {
    key: 'pb_ratio',
    label: 'P/B Ratio',
    type: 'raw',
    colorType: 'pe',
    meaning: 'Price ÷ Book Value per share. Book value is total assets minus total liabilities — what shareholders would theoretically receive if the company liquidated. A P/B above 1 means the market values the company above its accounting assets, typically because of brand, IP, or growth potential.',
    scale: '< 1× = Trading Below Book (Potential Value) · 1–3× = Normal · 3–10× = Growth Premium · > 10× = Asset-Light / Speculative',
  },
  {
    key: 'earnings_yoy',
    label: 'Earnings YoY',
    type: 'pct',
    colorType: 'margin',
    meaning: 'Year-over-year change in earnings per share (EPS). Revenue growth is good, but earnings growth confirms the company is becoming more profitable — not just bigger. Strong earnings growth usually drives stock price appreciation over time.',
    scale: '< 0% = EPS Shrinkage (Red) · 0–10% = Slow · 10–25% = Healthy · > 25% = Accelerating (Bright Green)',
  },
  {
    key: 'debt_to_equity',
    label: 'Debt / Equity',
    type: 'raw',
    colorType: 'warChest',
    meaning: 'Total Debt ÷ Total Shareholders\' Equity. Measures financial leverage. A high D/E ratio means the company is financed heavily by debt, which amplifies both gains and losses. Capital-intensive industries (utilities, telecom) naturally carry higher D/E ratios.',
    scale: '< 0.5 = Conservative (Green) · 0.5–1.5 = Normal · 1.5–3.0 = Elevated · > 3.0 = High Leverage (Red)',
  },
  {
    key: 'current_ratio',
    label: 'Current Ratio',
    type: 'raw',
    colorType: 'warChest',
    meaning: 'Current Assets ÷ Current Liabilities. Measures short-term liquidity — can the company pay its bills due within 12 months? A ratio above 1.5 means comfortable short-term financial health. Below 1 can signal cash flow stress.',
    scale: '< 1.0 = Short-Term Stress (Red) · 1.0–1.5 = Tight · 1.5–3.0 = Healthy (Green) · > 3.0 = Excess Cash (may be inefficient)',
  },
  {
    key: 'roe',
    label: 'Return on Equity',
    type: 'pct',
    colorType: 'margin',
    meaning: 'Net Income ÷ Shareholders\' Equity. Measures how efficiently management generates profit from shareholder capital. Warren Buffett uses ROE as a key indicator of durable competitive advantage. High ROE + low debt = exceptional business quality.',
    scale: '< 0% = Destroying Value (Red) · 0–10% = Weak · 10–20% = Solid · > 20% = Exceptional (Bright Green)',
  },
  {
    key: 'roa',
    label: 'Return on Assets',
    type: 'pct',
    colorType: 'margin',
    meaning: 'Net Income ÷ Total Assets. Measures how efficiently the company uses its assets to generate profit. Particularly useful for comparing companies within asset-heavy industries like manufacturing, airlines, or banks.',
    scale: '< 0% = Losing Money on Assets (Red) · 0–5% = Low · 5–10% = Good · > 10% = Asset-Efficient (Bright Green)',
  },
  {
    key: 'short_ratio',
    label: 'Short Ratio',
    type: 'raw',
    colorType: 'pe',
    meaning: 'Shares sold short ÷ average daily trading volume. Tells you how many days it would take all short sellers to cover their positions. High short interest can signal bearish institutional sentiment — but can also fuel a "short squeeze" if positive news arrives.',
    scale: '< 1 = Low Short Interest · 1–5 = Moderate · 5–10 = High (Contrarian Signal) · > 10 = Extreme Short Interest (Red)',
  },
  {
    key: 'insider_pct',
    label: 'Insider Ownership',
    type: 'pct',
    colorType: 'margin',
    meaning: 'Percentage of shares owned by company executives, directors, and major insiders. High insider ownership aligns management incentives with shareholders. When insiders own a large stake, they are motivated to grow the company\'s long-term value.',
    scale: '< 1% = Low Alignment · 1–5% = Some Skin · 5–20% = High Conviction (Green) · > 20% = Founder-Led Alignment',
  },
  {
    key: 'institution_pct',
    label: 'Institutional Ownership',
    type: 'pct',
    colorType: 'margin',
    meaning: 'Percentage of shares owned by hedge funds, mutual funds, pension funds, and other institutions. Very high institutional ownership means the stock is well-covered but also more vulnerable to coordinated selling. Very low means institutions haven\'t discovered it yet.',
    scale: '< 20% = Undiscovered / Ignored · 20–60% = Growing Interest · 60–80% = Well-Owned · > 80% = Highly Institutional (potential volatility)',
  },
]

export const TIMEFRAMES = ['1W', '1M', '6M', '1Y']
