// Segment → color mapping
export const SEGMENT_COLORS = {
  // Tech & Software
  TECH:        { bg: '#eff6ff', text: '#1d4ed8', border: '#bfdbfe' },
  AI:          { bg: '#f5f3ff', text: '#6d28d9', border: '#ddd6fe' },
  CLOUD:       { bg: '#ecfdf5', text: '#065f46', border: '#a7f3d0' },
  SEMIS:       { bg: '#fef3c7', text: '#92400e', border: '#fde68a' },
  SOFTWARE:    { bg: '#e0f2fe', text: '#075985', border: '#bae6fd' },
  CYBER:       { bg: '#fdf2f8', text: '#9d174d', border: '#fbcfe8' },
  SAAS:        { bg: '#ecfdf5', text: '#065f46', border: '#a7f3d0' },
  HARDWARE:    { bg: '#f0fdf4', text: '#166534', border: '#bbf7d0' },
  // Media & Consumer
  SOCIAL:      { bg: '#fff7ed', text: '#c2410c', border: '#fed7aa' },
  STREAMING:   { bg: '#fdf4ff', text: '#7e22ce', border: '#e9d5ff' },
  GAMING:      { bg: '#f0fdf4', text: '#15803d', border: '#bbf7d0' },
  ADS:         { bg: '#fff1f2', text: '#be123c', border: '#fecdd3' },
  MEDIA:       { bg: '#fefce8', text: '#854d0e', border: '#fef08a' },
  ECOM:        { bg: '#fff7ed', text: '#c2410c', border: '#fed7aa' },
  RETAIL:      { bg: '#fef9c3', text: '#713f12', border: '#fef08a' },
  // Finance
  BANKING:     { bg: '#eff6ff', text: '#1e40af', border: '#bfdbfe' },
  FINANCE:     { bg: '#eef2ff', text: '#4338ca', border: '#c7d2fe' },
  INSURANCE:   { bg: '#f0f9ff', text: '#0369a1', border: '#bae6fd' },
  FINTECH:     { bg: '#ecfdf5', text: '#047857', border: '#a7f3d0' },
  PAYMENTS:    { bg: '#f0fdf4', text: '#166534', border: '#bbf7d0' },
  // Health
  HEALTH:      { bg: '#f0fdf4', text: '#15803d', border: '#bbf7d0' },
  PHARMA:      { bg: '#ecfdf5', text: '#065f46', border: '#a7f3d0' },
  BIOTECH:     { bg: '#f5f3ff', text: '#5b21b6', border: '#ddd6fe' },
  MEDTECH:     { bg: '#eff6ff', text: '#1d4ed8', border: '#bfdbfe' },
  // Energy & Materials
  ENERGY:      { bg: '#fff7ed', text: '#b45309', border: '#fde68a' },
  OIL:         { bg: '#fefce8', text: '#78350f', border: '#fef08a' },
  RENEWABLES:  { bg: '#f0fdf4', text: '#166534', border: '#bbf7d0' },
  MINING:      { bg: '#f5f5f4', text: '#44403c', border: '#d6d3d1' },
  MATERIALS:   { bg: '#fafaf9', text: '#57534e', border: '#e7e5e4' },
  // Industry
  AUTO:        { bg: '#f0f9ff', text: '#0c4a6e', border: '#bae6fd' },
  EV:          { bg: '#ecfdf5', text: '#065f46', border: '#a7f3d0' },
  AERO:        { bg: '#eff6ff', text: '#1e40af', border: '#bfdbfe' },
  DEFENSE:     { bg: '#1a1a2e', text: '#e2e8f0', border: '#334155' },
  INDUSTRIAL:  { bg: '#fafaf9', text: '#44403c', border: '#d6d3d1' },
  LOGISTICS:   { bg: '#f0f9ff', text: '#0369a1', border: '#bae6fd' },
  INFRA:       { bg: '#f8fafc', text: '#334155', border: '#cbd5e1' },
  TELECOM:     { bg: '#fdf4ff', text: '#86198f', border: '#f0abfc' },
  // Real Estate & Utilities
  REIT:        { bg: '#fef2f2', text: '#991b1b', border: '#fecaca' },
  UTILITIES:   { bg: '#f1f5f9', text: '#475569', border: '#cbd5e1' },
  // Fund types
  ETF:         { bg: '#1e293b', text: '#f1f5f9', border: '#334155' },
  'INDEX ETF': { bg: '#0f172a', text: '#e2e8f0', border: '#1e293b' },
  DIVIDEND:    { bg: '#fdf4ff', text: '#7e22ce', border: '#e9d5ff' },
  BOND:        { bg: '#f1f5f9', text: '#334155', border: '#cbd5e1' },
  // Market cap
  'MEGA CAP':  { bg: '#111827', text: '#f9fafb', border: '#374151' },
  'LARGE CAP': { bg: '#1f2937', text: '#f3f4f6', border: '#4b5563' },
  'MID CAP':   { bg: '#374151', text: '#e5e7eb', border: '#6b7280' },
  'SMALL CAP': { bg: '#6b7280', text: '#fff',    border: '#9ca3af' },
  // Special
  DEFENSIVE:   { bg: '#fef2f2', text: '#991b1b', border: '#fecaca' },
  GROWTH:      { bg: '#ecfdf5', text: '#065f46', border: '#a7f3d0' },
  EQUITY:      { bg: '#f8fafc', text: '#475569', border: '#cbd5e1' },
}

// Comprehensive ticker → segments map (well-known global tickers)
const SEGMENTS_MAP = {
  // ── MEGA CAP TECH ──────────────────────────────
  AAPL:  ['TECH','MEGA CAP'],
  MSFT:  ['TECH','AI','MEGA CAP'],
  NVDA:  ['AI','SEMIS','MEGA CAP'],
  GOOGL: ['TECH','AI','ADS','MEGA CAP'],
  GOOG:  ['TECH','AI','ADS','MEGA CAP'],
  AMZN:  ['ECOM','CLOUD','AI','MEGA CAP'],
  META:  ['SOCIAL','AI','ADS','MEGA CAP'],
  TSM:   ['SEMIS','MEGA CAP'],
  AVGO:  ['SEMIS','AI'],
  ORCL:  ['CLOUD','SOFTWARE'],
  CRM:   ['SAAS','SOFTWARE'],
  SAP:   ['SOFTWARE','SAAS'],
  ADBE:  ['SOFTWARE','SAAS'],
  INTU:  ['FINTECH','SOFTWARE'],
  NOW:   ['SAAS','SOFTWARE'],
  SNOW:  ['CLOUD','SAAS'],
  PLTR:  ['AI','SOFTWARE'],
  SHOP:  ['ECOM','SAAS'],
  // ── SEMIS ─────────────────────────────────────
  AMD:   ['SEMIS','AI'],
  INTC:  ['SEMIS','HARDWARE'],
  QCOM:  ['SEMIS','TELECOM'],
  MU:    ['SEMIS'],
  AMAT:  ['SEMIS'],
  KLAC:  ['SEMIS'],
  LRCX:  ['SEMIS'],
  MRVL:  ['SEMIS','AI'],
  ARM:   ['SEMIS','AI'],
  ASML:  ['SEMIS'],
  // ── CONSUMER TECH / MEDIA ─────────────────────
  NFLX:  ['STREAMING','MEDIA'],
  DIS:   ['MEDIA','STREAMING'],
  SPOT:  ['STREAMING','MEDIA'],
  SNAP:  ['SOCIAL','ADS'],
  PINS:  ['SOCIAL','ADS'],
  RDDT:  ['SOCIAL','MEDIA'],
  TWTR:  ['SOCIAL','ADS'],
  BIDU:  ['AI','SOCIAL'],
  TCEHY: ['GAMING','SOCIAL','ECOM'],
  NTES:  ['GAMING'],
  EA:    ['GAMING'],
  TTWO:  ['GAMING'],
  RBLX:  ['GAMING','SOCIAL'],
  UBSFY: ['GAMING'],
  // ── ECOM / RETAIL ─────────────────────────────
  TSLA:  ['EV','AUTO'],
  F:     ['AUTO'],
  GM:    ['AUTO'],
  TM:    ['AUTO'],
  RIVN:  ['EV','AUTO'],
  LCID:  ['EV','AUTO'],
  NIO:   ['EV','AUTO'],
  BABA:  ['ECOM','CLOUD'],
  JD:    ['ECOM'],
  PDD:   ['ECOM'],
  MELI:  ['ECOM','FINTECH'],
  ETSY:  ['ECOM'],
  EBAY:  ['ECOM'],
  WMT:   ['RETAIL','ECOM'],
  TGT:   ['RETAIL'],
  COST:  ['RETAIL'],
  AMZN:  ['ECOM','CLOUD','MEGA CAP'],
  // ── FINANCE ───────────────────────────────────
  JPM:   ['BANKING','FINANCE','MEGA CAP'],
  BAC:   ['BANKING','FINANCE'],
  WFC:   ['BANKING','FINANCE'],
  GS:    ['BANKING','FINANCE'],
  MS:    ['BANKING','FINANCE'],
  C:     ['BANKING','FINANCE'],
  USB:   ['BANKING'],
  SCHW:  ['FINANCE'],
  BLK:   ['FINANCE'],
  AXP:   ['PAYMENTS','FINANCE'],
  V:     ['PAYMENTS','FINTECH'],
  MA:    ['PAYMENTS','FINTECH'],
  PYPL:  ['PAYMENTS','FINTECH'],
  SQ:    ['FINTECH','PAYMENTS'],
  AFRM:  ['FINTECH'],
  SOFI:  ['FINTECH','BANKING'],
  NU:    ['FINTECH','BANKING'],
  // ── INSURANCE ─────────────────────────────────
  BRK:   ['FINANCE','INSURANCE'],
  'BRK.B':['FINANCE','INSURANCE'],
  'BRK.A':['FINANCE','INSURANCE'],
  MET:   ['INSURANCE'],
  PRU:   ['INSURANCE','FINANCE'],
  AIG:   ['INSURANCE'],
  ALL:   ['INSURANCE'],
  CB:    ['INSURANCE'],
  // ── HEALTH ────────────────────────────────────
  JNJ:   ['HEALTH','PHARMA','DEFENSIVE'],
  UNH:   ['HEALTH','INSURANCE'],
  PFE:   ['PHARMA','HEALTH'],
  ABBV:  ['PHARMA','HEALTH'],
  LLY:   ['PHARMA','BIOTECH'],
  MRK:   ['PHARMA','HEALTH'],
  BMY:   ['PHARMA','HEALTH'],
  AMGN:  ['BIOTECH','PHARMA'],
  GILD:  ['BIOTECH','PHARMA'],
  BIIB:  ['BIOTECH'],
  REGN:  ['BIOTECH','PHARMA'],
  MRNA:  ['BIOTECH'],
  ISRG:  ['MEDTECH','HEALTH'],
  ABT:   ['MEDTECH','HEALTH'],
  MDT:   ['MEDTECH'],
  BSX:   ['MEDTECH'],
  SYK:   ['MEDTECH'],
  CVS:   ['HEALTH','RETAIL'],
  HUM:   ['HEALTH','INSURANCE'],
  ELV:   ['HEALTH','INSURANCE'],
  // ── ENERGY / OIL ──────────────────────────────
  XOM:   ['OIL','ENERGY'],
  CVX:   ['OIL','ENERGY'],
  COP:   ['OIL','ENERGY'],
  SLB:   ['ENERGY'],
  EOG:   ['OIL','ENERGY'],
  MPC:   ['OIL','ENERGY'],
  VLO:   ['OIL','ENERGY'],
  PSX:   ['OIL','ENERGY'],
  BP:    ['OIL','ENERGY'],
  SHEL:  ['OIL','ENERGY'],
  TTE:   ['OIL','ENERGY'],
  ENPH:  ['RENEWABLES','ENERGY'],
  FSLR:  ['RENEWABLES','ENERGY'],
  NEE:   ['UTILITIES','RENEWABLES'],
  PLUG:  ['RENEWABLES'],
  // ── DEFENSE / AERO ────────────────────────────
  LMT:   ['DEFENSE','AERO'],
  RTX:   ['DEFENSE','AERO'],
  NOC:   ['DEFENSE','AERO'],
  GD:    ['DEFENSE','AERO'],
  BA:    ['AERO'],
  AIR:   ['AERO'],
  // ── TELECOM ───────────────────────────────────
  T:     ['TELECOM'],
  VZ:    ['TELECOM'],
  TMUS:  ['TELECOM'],
  ERIC:  ['TELECOM','HARDWARE'],
  NOK:   ['TELECOM','HARDWARE'],
  ORAN:  ['TELECOM'],
  // ── INDUSTRIAL ────────────────────────────────
  CAT:   ['INDUSTRIAL'],
  DE:    ['INDUSTRIAL'],
  HON:   ['INDUSTRIAL','AERO'],
  GE:    ['INDUSTRIAL','AERO'],
  MMM:   ['INDUSTRIAL'],
  EMR:   ['INDUSTRIAL'],
  ETN:   ['INDUSTRIAL'],
  PH:    ['INDUSTRIAL'],
  FDX:   ['LOGISTICS'],
  UPS:   ['LOGISTICS'],
  AMGN:  ['BIOTECH'],
  // ── CYBER ─────────────────────────────────────
  CRWD:  ['CYBER','SOFTWARE'],
  PANW:  ['CYBER','SOFTWARE'],
  ZS:    ['CYBER','CLOUD'],
  FTNT:  ['CYBER','HARDWARE'],
  S:     ['CYBER'],
  OKTA:  ['CYBER','SAAS'],
  // ── REAL ESTATE ───────────────────────────────
  SPG:   ['REIT'],
  PLD:   ['REIT','LOGISTICS'],
  AMT:   ['REIT','TELECOM'],
  EQIX:  ['REIT','CLOUD'],
  O:     ['REIT','DIVIDEND'],
  // ── UTILITIES ─────────────────────────────────
  DUK:   ['UTILITIES','DEFENSIVE'],
  SO:    ['UTILITIES','DEFENSIVE'],
  AEP:   ['UTILITIES'],
  D:     ['UTILITIES'],
  EXC:   ['UTILITIES'],
  // ── ETFs ──────────────────────────────────────
  SPY:   ['INDEX ETF'],
  VOO:   ['INDEX ETF'],
  IVV:   ['INDEX ETF'],
  QQQ:   ['INDEX ETF'],
  VTI:   ['INDEX ETF'],
  VEA:   ['INDEX ETF'],
  VWO:   ['INDEX ETF'],
  DIA:   ['INDEX ETF'],
  IWM:   ['INDEX ETF'],
  GLD:   ['ETF'],
  SLV:   ['ETF'],
  TLT:   ['BOND','ETF'],
  AGG:   ['BOND','ETF'],
  BND:   ['BOND','ETF'],
  ARKK:  ['ETF','GROWTH'],
  ARKG:  ['ETF','BIOTECH'],
  SCHD:  ['ETF','DIVIDEND'],
  VYM:   ['ETF','DIVIDEND'],
  JEPI:  ['ETF','DIVIDEND'],
  XLK:   ['ETF','TECH'],
  XLF:   ['ETF','FINANCE'],
  XLE:   ['ETF','ENERGY'],
  XLV:   ['ETF','HEALTH'],
  XLI:   ['ETF','INDUSTRIAL'],
  SOXX:  ['ETF','SEMIS'],
  SMH:   ['ETF','SEMIS'],
  // ── CONSUMER STAPLES / DEFENSIVE ──────────────
  PG:    ['DEFENSIVE','RETAIL'],
  KO:    ['DEFENSIVE'],
  PEP:   ['DEFENSIVE'],
  MCD:   ['DEFENSIVE','RETAIL'],
  SBUX:  ['RETAIL','DEFENSIVE'],
  PM:    ['DEFENSIVE'],
  MO:    ['DEFENSIVE'],
  CL:    ['DEFENSIVE'],
  // ── COMMODITIES / MATERIALS ───────────────────
  NEM:   ['MINING','MATERIALS'],
  FCX:   ['MINING','MATERIALS'],
  RIO:   ['MINING','MATERIALS'],
  BHP:   ['MINING','MATERIALS'],
  AA:    ['MATERIALS'],
  DOW:   ['MATERIALS'],
  LIN:   ['MATERIALS'],
}

export function getStockSegments(ticker, isEtf = false) {
  if (!ticker) return ['EQUITY']
  const up = ticker.toUpperCase()
  if (SEGMENTS_MAP[up]) return SEGMENTS_MAP[up]
  if (isEtf) return ['ETF']
  return ['EQUITY']
}

export function getSegmentStyle(segment) {
  return SEGMENT_COLORS[segment] || SEGMENT_COLORS['EQUITY']
}
