-- ============================================================================
-- 1. CLEANUP EXISTING TABLES & OBJECTS
-- ============================================================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

DROP TABLE IF EXISTS public.follows CASCADE;
DROP TABLE IF EXISTS public.follow_requests CASCADE;
DROP TABLE IF EXISTS public.portfolio_holdings CASCADE;
DROP TABLE IF EXISTS public.portfolio_folders CASCADE;
DROP TABLE IF EXISTS public.portfolio_items CASCADE;
DROP TABLE IF EXISTS public.folders CASCADE;
DROP TABLE IF EXISTS public.global_metrics CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ============================================================================
-- 2. TABLE DEFINITIONS
-- ============================================================================

-- Profiles Table (Houses core user identifier metadata)
CREATE TABLE public.profiles (
    id uuid PRIMARY KEY,
    username text NULL,
    name text NULL,
    display_name text NULL, -- Adjusted to NULL to prevent frontend insertion mismatch failures
    avatar_url text NULL,
    portfolio_public bool NOT NULL DEFAULT false,
    created_at timestamptz NULL DEFAULT NOW()
);

-- Global Metrics Table (Caches market calculations and AI scan data strings)
CREATE TABLE public.global_metrics (
    ticker varchar PRIMARY KEY,
    revenue_yoy numeric NULL,
    fcf numeric NULL,
    war_chest_ratio numeric NULL,
    last_updated timestamptz NULL,
    ai_scan jsonb NULL
);

-- Folders Table (User Watchlists)
CREATE TABLE public.folders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    name varchar NOT NULL,
    created_at timestamptz NULL DEFAULT NOW()
);

-- Portfolio Items Table (Individual tickers within watchlists)
CREATE TABLE public.portfolio_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    folder_id uuid NOT NULL REFERENCES public.folders(id) ON DELETE CASCADE,
    ticker varchar NOT NULL,
    added_at timestamptz NULL DEFAULT NOW()
);

-- Portfolio Folders Table (Grouping mechanism for portfolio investment assets)
CREATE TABLE public.portfolio_folders (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    name text NOT NULL,
    is_public bool NULL DEFAULT false,
    created_at timestamptz NULL DEFAULT NOW()
);

-- Portfolio Holdings Table (Individual unit transactions per portfolio grouping)
CREATE TABLE public.portfolio_holdings (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    folder_id int8 NULL REFERENCES public.portfolio_folders(id) ON DELETE CASCADE,
    ticker text NOT NULL,
    amount numeric NOT NULL,
    buy_price numeric NOT NULL,
    created_at timestamptz NULL DEFAULT NOW()
);

-- Follow Requests Table (Pending user relationship connections)
CREATE TABLE public.follow_requests (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id uuid NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    target_user_id uuid NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status text NULL DEFAULT 'pending',
    created_at timestamptz NULL DEFAULT NOW()
);

-- Follows Table (Established active user follow associations)
CREATE TABLE public.follows (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    follower_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    followee_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- 3. AUTOMATED AUTH SYNC TRIGGER
-- ============================================================================
-- Guarantees a public profile row is created even if frontend background sync drops out
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, name, display_name, avatar_url, portfolio_public)
  VALUES (
    new.id,
    LOWER(TRIM(COALESCE(new.raw_user_meta_data->>'username', ''))),
    COALESCE(new.raw_user_meta_data->>'name', ''),
    COALESCE(new.raw_user_meta_data->>'name', ''),
    COALESCE(new.raw_user_meta_data->>'avatar_url', NULL),
    false
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- 4. ROW LEVEL SECURITY (RLS) INITIALIZATION
-- ============================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_holdings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follow_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 5. FINE-GRAINED SECURITY POLICIES
-- ============================================================================

-- --- PROFILES POLICIES ---
CREATE POLICY "Allow public read access to profiles" 
    ON public.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow users to update own profile" 
    ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

CREATE POLICY "Allow system profile insertion" 
    ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

-- --- GLOBAL METRICS POLICIES ---
CREATE POLICY "Allow authenticated read to global metrics" 
    ON public.global_metrics FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow write modification access to data handlers" 
    ON public.global_metrics FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- --- WATCHLIST FOLDERS & ITEMS POLICIES ---
CREATE POLICY "Manage individual watchlist folders" 
    ON public.folders FOR ALL TO authenticated 
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Manage individual watchlist items" 
    ON public.portfolio_items FOR ALL TO authenticated 
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- --- PORTFOLIO FOLDERS POLICIES ---
CREATE POLICY "Allow owners full control over portfolio folders" 
    ON public.portfolio_folders FOR ALL TO authenticated 
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow viewing of public portfolio folders" 
    ON public.portfolio_folders FOR SELECT TO authenticated 
    USING (
        is_public = true 
        OR auth.uid() = user_id 
        OR EXISTS (
            SELECT 1 FROM public.follows 
            WHERE follower_id = auth.uid() 
              AND followee_id = portfolio_folders.user_id 
              AND status = 'accepted'
        )
    );

-- --- PORTFOLIO HOLDINGS POLICIES ---
CREATE POLICY "Allow owners full control over holdings" 
    ON public.portfolio_holdings FOR ALL TO authenticated 
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow viewing holdings inside accessible folders" 
    ON public.portfolio_holdings FOR SELECT TO authenticated 
    USING (
        auth.uid() = user_id 
        OR EXISTS (
            SELECT 1 FROM public.portfolio_folders f
            WHERE f.id = portfolio_holdings.folder_id 
              AND (
                f.is_public = true 
                OR EXISTS (
                    SELECT 1 FROM public.follows fol 
                    WHERE fol.follower_id = auth.uid() 
                      AND fol.followee_id = f.user_id 
                      AND fol.status = 'accepted'
                )
              )
        )
    );

-- --- FOLLOW REQUESTS & RELATIONS POLICIES ---
CREATE POLICY "Manage involved follow requests" 
    ON public.follow_requests FOR ALL TO authenticated 
    USING (auth.uid() = requester_user_id OR auth.uid() = target_user_id)
    WITH CHECK (auth.uid() = requester_user_id OR auth.uid() = target_user_id);

CREATE POLICY "Manage visible follow relationships" 
    ON public.follows FOR ALL TO authenticated 
    USING (auth.uid() = follower_id OR auth.uid() = followee_id)
    WITH CHECK (auth.uid() = follower_id OR auth.uid() = followee_id);

-- ============================================================================
-- 6. INDEX OPTIMIZATION KEYSTROKES
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_folders_user_id ON public.folders(user_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_items_folder_id ON public.portfolio_items(folder_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_folders_user_id ON public.portfolio_folders(user_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_holdings_folder_id ON public.portfolio_holdings(folder_id);
CREATE INDEX IF NOT EXISTS idx_follows_follower_id ON public.follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_followee_id ON public.follows(followee_id);