-- ============================================================================
-- CLEANUP EXISTING WORKSPACE OBJECTS
-- ============================================================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

DROP TABLE IF EXISTS public.follows CASCADE;
DROP TABLE IF EXISTS public.follow_requests CASCADE;
DROP TABLE IF EXISTS public.portfolio_holdings CASCADE;
DROP TABLE IF EXISTS public.portfolio_folders CASCADE;
DROP TABLE IF EXISTS public.portfolio_items CASCADE;
DROP TABLE IF EXISTS public.folders CASCADE;
DROP TABLE IF EXISTS public.global_metrics CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ============================================================================
-- TABLE INITIALIZATION
-- ============================================================================

-- 1. Profiles Table
CREATE TABLE public.profiles (
    id uuid PRIMARY KEY,
    username text NULL,
    name text NULL,
    display_name text NULL, 
    avatar_url text NULL,
    portfolio_public bool NOT NULL DEFAULT false,
    created_at timestamptz NULL DEFAULT NOW()
);

-- 2. Global Metrics Table
-- lightweight known-tickers lookup only — the metric/AI columns this table
-- used to have are dead (nothing populates or reads them since the nightly
-- engine.py job was removed; metrics are computed live by the backend now)
CREATE TABLE public.global_metrics (
    ticker varchar PRIMARY KEY
);

-- 3. Watchlist Folders Table
CREATE TABLE public.folders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    name varchar NOT NULL,
    created_at timestamptz NULL DEFAULT NOW()
);

-- 4. Watchlist Items Table
CREATE TABLE public.portfolio_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    folder_id uuid NOT NULL REFERENCES public.folders(id) ON DELETE CASCADE,
    ticker varchar NOT NULL,
    added_at timestamptz NULL DEFAULT NOW(),
    CONSTRAINT unique_folder_ticker UNIQUE (folder_id, ticker)
);

-- 5. Portfolio Folders Table
CREATE TABLE public.portfolio_folders (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    name text NOT NULL,
    is_public bool NULL DEFAULT false,
    created_at timestamptz NULL DEFAULT NOW()
);

-- 6. Portfolio Holdings Table
CREATE TABLE public.portfolio_holdings (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    folder_id int8 NULL REFERENCES public.portfolio_folders(id) ON DELETE CASCADE,
    ticker text NOT NULL,
    amount numeric NOT NULL,
    buy_price numeric NOT NULL,
    created_at timestamptz NULL DEFAULT NOW()
);

-- 7. Follow Requests Table
CREATE TABLE public.follow_requests (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id uuid NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    target_user_id uuid NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status text NULL DEFAULT 'pending',
    created_at timestamptz NULL DEFAULT NOW(),
    CONSTRAINT unique_requester_target UNIQUE (requester_user_id, target_user_id)
);

-- ============================================================================
-- AUTOMATED AUTH SIGNUP ROUTING TRIGGER
-- ============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, name, display_name, avatar_url, portfolio_public)
  VALUES (
    new.id,
    LOWER(TRIM(COALESCE(new.raw_user_meta_data->>'username', ''))),
    COALESCE(new.raw_user_meta_data->>'name', ''),
    COALESCE(new.raw_user_meta_data->>'name', ''),
    COALESCE(new.raw_user_meta_data->>'avatar_url', NULL),
    false
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- ROW LEVEL SECURITY RULES (RLS)
-- ============================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_holdings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follow_requests ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Profiles are readable by authenticated users" 
    ON public.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can manage their own profile" 
    ON public.profiles FOR ALL TO authenticated USING (auth.uid() = id);

-- Global Metrics Policies
CREATE POLICY "Global metrics are readable by authenticated users" 
    ON public.global_metrics FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can initialize missing tickers into metrics" 
    ON public.global_metrics FOR INSERT TO authenticated WITH CHECK (true);

-- no UPDATE policy: this table only holds a ticker PK now (see table def
-- above), so there is nothing for a client to legitimately update. the old
-- UPDATE policy allowed any authenticated user to overwrite any row in this
-- shared/global table — removed as a real data-poisoning risk.

-- Watchlist Folders Policies
CREATE POLICY "Users have full control over own watchlist folders" 
    ON public.folders FOR ALL TO authenticated 
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Watchlist Ticker Items Policies
CREATE POLICY "Users have full control over own watchlist assets" 
    ON public.portfolio_items FOR ALL TO authenticated 
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Portfolio Folders Policies
CREATE POLICY "Users have full control over own investment folders" 
    ON public.portfolio_folders FOR ALL TO authenticated 
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Followers and public can review designated folders" 
    ON public.portfolio_folders FOR SELECT TO authenticated 
    USING (
        is_public = true 
        AND EXISTS (
            SELECT 1 FROM public.follow_requests
            WHERE requester_user_id = auth.uid()
              AND target_user_id = portfolio_folders.user_id
              AND status = 'accepted'
        )
        OR auth.uid() = user_id
    );

-- Portfolio Holdings Policies
CREATE POLICY "Users have full control over own item holdings" 
    ON public.portfolio_holdings FOR ALL TO authenticated 
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Followers can view holdings inside shared folders" 
    ON public.portfolio_holdings FOR SELECT TO authenticated 
    USING (
        auth.uid() = user_id
        OR EXISTS (
            SELECT 1 FROM public.portfolio_folders pf
            WHERE pf.id = portfolio_holdings.folder_id
              AND pf.is_public = true
              AND EXISTS (
                  SELECT 1 FROM public.follow_requests fr
                  WHERE fr.requester_user_id = auth.uid()
                    AND fr.target_user_id = pf.user_id
                    AND fr.status = 'accepted'
              )
        )
    );

-- Follow Requests Policies
CREATE POLICY "Involved parties can manage follow requests" 
    ON public.follow_requests FOR ALL TO authenticated 
    USING (auth.uid() = requester_user_id OR auth.uid() = target_user_id)
    WITH CHECK (auth.uid() = requester_user_id OR auth.uid() = target_user_id);

-- ============================================================================
-- PERFORMANCE OPTIMIZATION INDEXES
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_folders_user_id ON public.folders(user_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_items_folder_id ON public.portfolio_items(folder_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_folders_user_id ON public.portfolio_folders(user_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_holdings_folder_id ON public.portfolio_holdings(folder_id);
CREATE INDEX IF NOT EXISTS idx_follow_requests_lookup ON public.follow_requests(requester_user_id, target_user_id, status);

-- case-insensitive username uniqueness. previously only enforced in
-- useAuth.js via a check-then-insert, which is a race condition — two
-- simultaneous signups could both pass the check.
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_username_unique
    ON public.profiles (lower(username))
    WHERE username IS NOT NULL AND username <> '';